version: "v0.1.0"
env: "dev"

replicaCount: 1

image:
  repository: nizar968/api
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 80

datadog:
  enabled: "true"
  language: dotnet
