apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    tags.datadoghq.com/env: {{ .Values.env }}
    tags.datadoghq.com/service: {{ .Chart.Name }}
    tags.datadoghq.com/version: {{ .Values.version | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        tags.datadoghq.com/env: {{ .Values.env }}
        tags.datadoghq.com/service: {{ .Chart.Name }}
        tags.datadoghq.com/version: {{ .Values.version | quote }}
        admission.datadoghq.com/enabled: {{ .Values.datadog.enabled | quote }}
      annotations:
      {{ if eq .Values.datadog.language "dotnet" }}
        admission.datadoghq.com/dotnet-lib.version: v2.46.0
      {{ end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DD_LOGS_INJECTION
              value: {{ .Values.datadog.enabled | quote }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
